name: S3 Synchronisation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: jakejarvis/s3-sync-action@master
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exclude '.git/*' --exclude '.github/*' --exclude '.vscode/*' --exclude 'README.md' --exclude '.gitignore' --exclude '.env' --exclude '.gitattributes' --exclude '.editorconfig' --exclude '.prettierrc' --exclude '.github/workflows/*'
        env:
          AWS_S3_BUCKET: 'realtime-logs-processing'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          DEST_DIR: 'weblogs'

     